### PR TITLE
61 expose version in management api

### LINKED ISSUE #61: expose version in management API
Motivation: app version info is useful for bug reports and investigation.

- [ ] crete endpoint with worker version
- [ ] request and print also backend version in `chorctl` in `chorctl --version`

### PR DESCRIPTION
**Pull request by aiivashchenko**
Closes #61

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+	GOBIN=$(TOOLS_DIR) go install golang.org/x/tools/cmd/goimports@latest
+	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(TOOLS_DIR) $(GOLANGCI_LINT_VERSION)
+	GOBIN=$(TOOLS_DIR) go install "google.golang.org/protobuf/cmd/protoc-gen-go@$(PROTOC_GEN_GO_VERSION)"
+	GOBIN=$(TOOLS_DIR) go install "google.golang.org/grpc/cmd/protoc-gen-go-grpc@$(PROTOC_GEN_GO_GRPC_VERSION)"
+	GOBIN=$(TOOLS_DIR) go install "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@$(PROTOC_GEN_GO_GRPC_GATEWAY_VERSION)"
+	GOBIN=$(TOOLS_DIR) go install "github.com/bufbuild/buf/cmd/buf@$(BUF_VERSION)"
+	GOBIN=$(TOOLS_DIR) go install "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@$(PROTOC_GEN_OPENAPIV2_VERSION)"
+
+.PHONY: ensure-tools
+ensure-tools:
```
Comment (arttor) [inline Makefile:29]: will it work with tool version upgrade?

I think that it is better to just run `install-tools` because `go install` already has cache.

File: Makefile [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+BUF_VERSION="v1.45.0"
+PROTOC_GEN_OPENAPIV2_VERSION="v2.15.2"
+
+.PHONY: all
+all: agent chorus proxy worker chorctl bench
+
+.PHONY: install-tools
+install-tools:
+	mkdir -p $(TOOLS_DIR)
+	GOBIN=$(TOOLS_DIR) go install golang.org/x/tools/cmd/goimports@latest
```
Comment (arttor) [inline Makefile:20]: will it be better to use fixed version?

File: Makefile [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+.PHONY: vet
+vet:
+	go vet ./...
+
+.PHONY: fmt
+fmt:
+	go fmt ./...
+
+.PHONY: imports
+imports:
```
Comment (arttor) [inline Makefile:47]: why do we need to call imports for every dir? what will happen if someone will add a new dir?

File: Makefile [hunk 4]
```diff
@@ -0,0 +1,101 @@
+TOOLS_DIR="$(PWD)/.tools"
```
Comment (arttor) [inline Makefile:1]: should we use make on CI?

File: Makefile [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+	$(TOOLS_DIR)/golangci-lint run
+
+.PHONY: pretty
+pretty: tidy fmt vet imports lint
+
+.PHONY: mkdir-build
+mkdir-build: 
+	mkdir -p build
+
+%-bin: ensure-tools pretty mkdir-build
```
Comment (arttor) [inline Makefile:64]: can you add comment what this command does?

File: Makefile [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+.PHONY: agent
+agent: agent-bin
+	go build -ldflags="-X 'main.date=$(BUILD_DATE)' -X 'main.version=$(GIT_TAG)' -X 'main.commit=$(GIT_COMMIT)'" -o build/agent cmd/agent/main.go
+
+.PHONY: chorus
+chorus: chorus-bin
+	go build -ldflags="-X 'main.date=$(BUILD_DATE)' -X 'main.version=$(GIT_TAG)' -X 'main.commit=$(GIT_COMMIT)'" -o build/chorus cmd/chorus/main.go
+
+.PHONY: proxy
+proxy: proxy-bin
```
Comment (arttor) [inline Makefile:76]: should make be used in Dockerfile and goreleaser?

File: pkg/rpc/agent_redis_request_reply.go [hunk 7]
```diff
@@ -46,8 +47,10 @@ type AgentInfo struct {
 func (a *AgentClient) Ping(ctx context.Context) ([]AgentInfo, error) {
 	replyChanName := xid.New().String()
 	ps := a.client.Subscribe(ctx, replyChanName)
-	defer ps.Close()
-	defer ps.Unsubscribe(context.Background(), replyChanName)
+	defer func() {
+		_ = ps.Close()
+		_ = ps.Unsubscribe(context.Background(), replyChanName)
+	}()
```
Comment (arttor) [inline pkg/rpc/agent_redis_request_reply.go:53]: is this change required by linter or it is for readability?

File: proto/chorus/chorus.proto [hunk 8]
```diff
@@ -9,10 +9,13 @@ import "google/protobuf/empty.proto";
 
 
 service Chorus {
+  // Get app version
+  rpc GetAppVersion(google.protobuf.Empty) returns (GetAppVersionResponse);
```
Comment (arttor) [inline proto/chorus/chorus.proto:13]: add mapping to [http.yaml](https://github.com/clyso/chorus/blob/main/proto/http.yaml) for REST endpoint

File: service/proxy/router/server.go [hunk 9]
```diff
@@ -46,11 +48,11 @@ func Serve(router Router, replSvc replication.Service) *http.ServeMux {
 			}
 		}()
 		ctx = log.WithStorage(ctx, storage)
+		// TODO: is it reachable? This branch is active only if err == nil
```
Comment (arttor) [inline service/proxy/router/server.go:51]: yes it is reachable

**Review by arttor — CHANGES_REQUESTED** [review]

File: Makefile (hunk 1 above)
Comment (aiivashchenko) [reply Makefile:29]: At the moment it checks only that tools are installed to the directory.

`go install` will not work with `golangci-lint`, as it has different installation method.

File: Makefile (hunk 3 above)
Comment (aiivashchenko) [reply Makefile:47]: It is made to exclude generated code, i.e. proto files, from formatting. 

`goimports` has an open issue to do this automatically, but so far it is not implemented.

File: Makefile (hunk 5 above)
Comment (aiivashchenko) [reply Makefile:69]: Added comment

File: pkg/rpc/agent_redis_request_reply.go (hunk 7 above)
Comment (aiivashchenko) [reply pkg/rpc/agent_redis_request_reply.go:53]: It is required by linter, as all ignored return values should be discarded explicitly.

File: Makefile (hunk 4 above)
Comment (aiivashchenko) [reply Makefile:1]: It can be done, but common steps in github workflows, e.g. linter step, are usually having their own configuration and way to run them.

File: proto/chorus/chorus.proto (hunk 8 above)
Comment (aiivashchenko) [reply proto/chorus/chorus.proto:13]: Added

File: service/proxy/router/server.go (hunk 9 above)
Comment (aiivashchenko) [reply service/proxy/router/server.go:51]: I've added this comment because it looks suspicious.

`err != nil` check is performed on L39. If it is successful, then function exits.

However, on L52, we are checking error type and logging error itself.

If it works in some other way, it is worth to explain it.

File: Makefile (hunk 6 above)
Comment (aiivashchenko) [reply Makefile:81]: For the dockerfile that is something that can be decided. Can't comment on `goreleaser` tho.

File: Makefile (hunk 1 above)
Comment (arttor) [reply Makefile:30]: maybe we can move `golangci-lint` installation to a separate step then?

File: Makefile (hunk 3 above)
Comment (arttor) [reply Makefile:48]: is there enough benefits of using`goimports ` in this case?
maybe we can introduce it later when it will be fixed?

File: Makefile (hunk 6 above)
Comment (arttor) [reply Makefile:81]: i can see that this command is different from the one used in Dockerfile. It introduces `main.date=$(BUILD_DATE)'` which is not used in Docker builds and probaly won't be presented in binaries produced by goreleaser and published in github release.

File: service/proxy/router/server.go (hunk 9 above)
Comment (arttor) [reply service/proxy/router/server.go:51]: i think you are right. if i remember it correctly, if err!=nil, we can additionnaly check if it was s3 api error or some other error like network problem.
See: https://github.com/clyso/chorus/blob/main/pkg/s3client/http_client.go#L243-L263

File: Makefile (hunk 3 above)
Comment (aiivashchenko) [reply Makefile:48]: It unifies formatting of imports and simplifies navigation through import block.

I don't think that manual exclusion of a folder brings a lot of disadvantages.

File: Makefile (hunk 6 above)
Comment (aiivashchenko) [reply Makefile:81]: True. I've added timestamp to the docker and workflow as well.

File: service/proxy/router/server.go (hunk 9 above)
Comment (arttor) [reply service/proxy/router/server.go:51]: lets do later

File: Makefile (hunk 3 above)
Comment (arttor) [reply Makefile:48]: ok

File: service/proxy/router/server.go (hunk 9 above)
Comment (aiivashchenko) [reply service/proxy/router/server.go:51]: Made #67 to cover it.

File: Makefile (hunk 1 above)
Comment (aiivashchenko) [reply Makefile]: Remade, now version is validated for linter as well.

**Review by arttor — APPROVED** [review]
