### PR TITLE
bugfix: cleanup on replication delete

### LINKED ISSUE #53: repl does not re-sync objects which were uploaded while replicating
If an object was uploaded through the chorus proxy while a replication is active and and running, and the target of the replication is lost, chorus does not re-sync this object if the repl is restarted. `chorctl repl` and `chorctl dash` claim that the objects have been synced, but the objects in question are missing in the target bucket. `chorus check` successfully identifies the missing objects.

This behavior can be reproduced using the standalone chorus version with the default config, but can also be observed when real s3-compatible backends are used

### steps to reproduce

**Note:** In my examples, the config  slightly differs from the default, because the default ports where already used by an other instance. The concrete configuration and the used s3 backends are not relevant for the issue. The following steps to reproduce the issue have been tested with several different s3 compatible backends.

**Note:** I am using a custom implementation of s3curl here, but the problem is independent from the used client.

1. start chorus standalone:
```
root@s3float-01:~/git/chorus# go run ./cmd/chorus/ -config /root/.config/chorus/test.yaml 
_________ .__                               
\_   ___ \|  |__   ___________ __ __  ______
/    \  \/|  |  \ /  _ \_  __ \  |  \/  ___/
\     \___|   Y  (  <_> )  | \/  |  /\___ \ 
 \______  /___|  /\____/|__|  |____//____  >
        \/     \/                        \/




S3 Proxy URL:   http://127.0.0.1:8669
S3 Proxy Credentials (AccessKey|SecretKey): 
 - user1: [testKey1|testSecretKey1]

GRPC mgmt API:  127.0.0.1:8670
HTTP mgmt API:  http://127.0.0.1:8671
Redis URL:      127.0.0.1:39275

Storage list:
 - [FAKE] one: http://127.0.0.1:8680 < MAIN
 - [FAKE] two: http://127.0.0.1:8681
```

2. create bucket on source and target, add replication:
```
root@s3float-01:~# ./s3curl.doomguy.pl -id chorustest http://127.0.0.1:8680/foo --createBucket -- -s

root@s3float-01:~# ./s3curl.doomguy.pl -id chorustest http://127.0.0.1:8681/foo --createBucket -- -s

root@s3float-01:~# chorctl -a 127.0.0.1:8670 repl add -f one -t two -b foo -u user1
root@s3float-01:~# chorctl -a 127.0.0.1:8670 repl 
NAME                   PROGRESS                 SIZE        OBJECTS     EVENTS     PAUSED     LAG       AGE
user1:foo:one->two     [          ]   0.0 %     0 B/0 B     0/0         0/0        false      ?         27s
```

3. upload some files, check replication:
```
root@s3float-01:~# ./s3curl.doomguy.pl -id chorustest http://127.0.0.1:8669/foo/first -put ./data/tree01/00/file_256 -- -s

root@s3float-01:~# ./s3curl.doomguy.pl -id chorustest http://127.0.0.1:8669/foo/second -put ./data/tree01/00/file_256 -- -s

root@s3float-01:~# chorctl -a 127.0.0.1:8670 repl
NAME                   PROGRESS                 SIZE        OBJECTS     EVENTS     PAUSED     LAG       AGE
user1:foo:one->two     [          ]   0.0 %     0 B/0 B     0/0         2/2        false      0s        6m
root@s3float-01:~# chorctl -a 127.0.0.1:8670 check one two -u user1
Getting list of buckets...
Start check for 1 buckets...
🪣 BUCKET | Match        | MissSrc       | MissDst       | Differ        | Error        |
✅ foo... | 2            | 0             | 0             | 0             | 0      

```

4. stop replication, delete objects on destination
```
root@s3float-01:~# ./s3curl.doomguy.pl -id chorustest http://127.0.0.1:8681/foo/first -delete -- -s

root@s3float-01:~# ./s3curl.doomguy.pl -id chorustest http://127.0.0.1:8681/foo/second -delete -- -s

root@s3float-01:~# chorctl -a 127.0.0.1:8670 check one two -b foo -u user1
Checking files in bucket foo ...
🪣 BUCKET | Match        | MissSrc       | MissDst       | Differ        | Error
❌ foo... | 0            | 0             | 2             | 0             | 0  
```

5. upload another object, restart replication
```
root@s3float-01:~# ./s3curl.doomguy.pl -id chorustest http://127.0.0.1:8669/foo/third -put ./data/tree01/00/file_256 -- -s

root@s3float-01:~# chorctl -a 127.0.0.1:8670 repl add -f one -t two -b foo -u user1
```

6. a) check state. The objects which have been uploaded while the original replication was running are missing in the destination bucket. The object which was added after the replication was deleted has been synced to the target.
```
root@s3float-01:~# chorctl -a 127.0.0.1:8670 check one two -b foo -u user1
Checking files in bucket foo ...
🪣 BUCKET | Match        | MissSrc       | MissDst       | Differ        | Error
❌ foo... | 1            | 0             | 2             | 0             | 0      
root@s3float-01:~# ./s3curl.doomguy.pl -id chorustest http://127.0.0.1:8680/foo/ -- -s
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>foo</Name>
  <IsTruncated>false</IsTruncated>
  <Prefix></Prefix>
  <MaxKeys>1000</MaxKeys>
  <Contents>
    <Key>first</Key>
    <LastModified>2024-12-11T13:41:48.826Z</LastModified>
    <ETag>&#34;bbaf2bba6b2a3e903607336eb1361bc7&#34;</ETag>
    <Size>13631488</Size>
  </Contents>
  <Contents>
    <Key>second</Key>
    <LastModified>2024-12-11T13:25:51.273Z</LastModified>
    <ETag>&#34;bbaf2bba6b2a3e903607336eb1361bc7&#34;</ETag>
    <Size>13631488</Size>
  </Contents>
  <Contents>
    <Key>third</Key>
    <LastModified>2024-12-11T13:43:28.008Z</LastModified>
    <ETag>&#34;bbaf2bba6b2a3e903607336eb1361bc7&#34;</ETag>
    <Size>13631488</Size>
  </Contents>
  <Marker></Marker>
</ListBucketResult>
root@s3float-01:~# ./s3curl.doomguy.pl -id chorustest http://127.0.0.1:8681/foo/ -- -s
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>foo</Name>
  <IsTruncated>false</IsTruncated>
  <Prefix></Prefix>
  <MaxKeys>1000</MaxKeys>
  <Contents>
    <Key>third</Key>
    <LastModified>2024-12-11T13:43:35.238Z</LastModified>
    <ETag>&#34;bbaf2bba6b2a3e903607336eb1361bc7&#34;</ETag>
    <Size>13631488</Size>
  </Contents>
  <Marker></Marker>
</ListBucketResult>
```

6. b) check replication status. chorus claims that all 3 objects have been processed
```
root@s3float-01:~# chorctl -a 127.0.0.1:8670 repl
NAME                   PROGRESS                 SIZE                  OBJECTS     EVENTS     PAUSED     LAG            AGE
user1:foo:one->two     [##########] 100.0 %     39.0 MiB/39.0 MiB     3/3         0/0        false      4.806161ms     5m
```

### PR DESCRIPTION
**Pull request by arttor**
Closes #53

### CODE REVIEW

File: pkg/meta/version_service.go [hunk 1]
```diff
@@ -44,6 +45,20 @@ else
...
+
+local scan_result = redis.call('SCAN', cursor, 'MATCH', pattern, 'COUNT', count)
+local new_cursor = tonumber(scan_result[1])
+local keys = scan_result[2]
+
+for _, key in ipairs(keys) do
+    redis.call('HDEL', key, field)
+end
+
+return new_cursor`)
```
Comment (aiivashchenko) [inline pkg/meta/version_service.go:61]: I'd move lua script to constants for the readability.

File: pkg/meta/version_service.go [hunk 2]
```diff
@@ -55,7 +70,7 @@ type VersionService interface {
 	UpdateIfGreater(ctx context.Context, obj dom.Object, storage string, version int64) error
 	// DeleteObjAll deletes all obj meta for all storages
 	DeleteObjAll(ctx context.Context, obj dom.Object) error
-	// DeleteBucketMeta deletes meta of bucket objects for given storage.
+	// DeleteBucketMeta deletes all versions info for bucket and all bucket objects
```
Comment (aiivashchenko) [inline pkg/meta/version_service.go:73]: Is it really deletes everything in bucket or just metadata?

File: pkg/storage/storage_test.go [hunk 3]
```diff
@@ -96,6 +96,24 @@ func Test_svc_GetLastListedObj(t *testing.T) {
 			}
 		}
 	}
+	r.NoError(storage.CleanLastListedObj(ctx, s1.FromStorage, s1.ToStorage, b1))
+	for i, stor := range stors {
+		for j, buck := range bucks {
+			for k, pref := range prefs {
```
Comment (aiivashchenko) [inline pkg/storage/storage_test.go:102]: Would be easier to read if indices would be named as `storeIdx`, `jucketIdx`, `prefIdx`

File: pkg/meta/version_service_test.go [hunk 4]
```diff
@@ -317,3 +317,167 @@ func Test_inc_version_during_switch(t *testing.T) {
...
+
+	ver, err = s.GetBucketTags(ctx, b1)
+	r.NoError(err)
+	r.Zero(ver[s1])
+	r.EqualValues(2, ver[s2])
+
+	ver, err = s.GetBucketTags(ctx, b2)
+	r.NoError(err)
+	r.EqualValues(1, ver[s1])
+	r.EqualValues(2, ver[s2])
```
Comment (aiivashchenko) [inline pkg/meta/version_service_test.go:482]: Would be nice to have some comments on this. 

E.g. why exactly these values are checked on delete bucket meta operation.

File: pkg/storage/storage.go [hunk 5]
```diff
@@ -29,10 +29,20 @@ const (
 	lastListedObjTTL = time.Hour * 8
 )
 
+var (
+	luaDeleteKeysByPrefix = redis.NewScript(`local keys = redis.call('keys', ARGV[1])
+if #keys >0 then
+	return redis.call('DEL', unpack(keys))
+else
+	return 0
+end`)
```
Comment (aiivashchenko) [inline pkg/storage/storage.go:38]: I'd move lua script to constants for the readability.

File: pkg/meta/version_service.go (hunk 1 above)
Comment (arttor) [reply pkg/meta/version_service.go:61]: i think that it is readable since it is only wrapped with `redis.NewScript()`. Otherwise there will be a set of consts and set of vars with similar names. Or we will have to call `redis.NewScript()` on each script invocation. But in this case we will be calculating script hash every time.

File: pkg/storage/storage_test.go (hunk 3 above)
Comment (arttor) [reply pkg/storage/storage_test.go]: fixed

File: pkg/meta/version_service_test.go (hunk 4 above)
Comment (arttor) [reply pkg/meta/version_service_test.go:482]: i agree that test is very verbose. it sets all possible bucket and object version metadata for 2 buckets in 2 storages. then it calls `DeleteBucketMeta(bucket, storage)` and tests that that metadata only for given `<bucket, storage>` combination was removed and all other metadata is still there.

File: pkg/meta/version_service.go (hunk 2 above)
Comment (arttor) [reply pkg/meta/version_service.go]: thanks, it was really poor wording. there are bucket version metadata in redis and obj version metadata in redis. here we remove only metadata in redis. fixed.

File: pkg/meta/version_service.go (hunk 1 above)
Comment (aiivashchenko) [reply pkg/meta/version_service.go:61]: > Otherwise there will be a set of consts and set of vars with similar names

I'd actually prefer this option.

Comment (aiivashchenko) [reply pkg/meta/version_service.go:61]: Also, one of the options can be to use separate files for lua scripts, like

```go
import _ "embed"

//go:embed script.lua
var luaScript string
```

Comment (arttor) [reply pkg/meta/version_service.go:61]: > I'd actually prefer this option. Anyways, compiler would do the same.

I'd like to keep current approach for several reasons:
- it is not useful to have named constant for string with exactly one usage
- when it may increase readabily it will multiply optoins in code completion
- we will have to change scripts in all files to have the same style across the project 
- [go-redis examples](https://github.com/redis/go-redis/blob/master/example/lua-scripting/main.go) and projects like asynq also using single vars.

> Also, one of the options can be to use separate files for lua scripts, like

i like this option because it enables syntax highlight but i don't know if it is worth it to have a separate file for each script.

**Review by aiivashchenko — APPROVED** [review]
